import { Cuisine, FoodTruck, MenuItem, Review, User, OwnerProfile } from './types';

export const foodTrucks: FoodTruck[] = [
  {
    id: '1',
    name: 'Aussie Bites',
    description: 'Authentic Australian street food with a modern twist. We specialize in gourmet meat pies, sausage rolls, and classic Aussie burgers that will make you feel right at home.',
    image: 'https://images.pexels.com/photos/2227960/pexels-photo-2227960.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    cuisine: 'Australian',
    rating: 4.7,
    reviewCount: 124,
    menu: [
      {
        id: 'm1',
        name: 'Classic Aussie Burger',
        description: 'Beef patty with beetroot, pineapple, egg, bacon, lettuce, and special sauce',
        price: 15.95,
        popular: true,
      },
      {
        id: 'm2',
        name: 'Meat Pie',
        description: 'Traditional Aussie meat pie with flaky pastry and rich gravy',
        price: 8.95,
      },
      {
        id: 'm3',
        name: 'Sausage Roll',
        description: 'Savory sausage wrapped in buttery puff pastry',
        price: 7.95,
      },
      {
        id: 'm4',
        name: 'Lamington',
        description: 'Sponge cake dipped in chocolate and coconut',
        price: 4.95,
        dietary: ['Vegetarian'],
      },
    ],
    location: {
      text: 'Bondi Beach, Sydney',
      coordinates: {
        lat: -33.8915,
        lng: 151.2767,
      },
    },
    schedule: [
      { day: 'Monday', open: '10:00', close: '20:00' },
      { day: 'Tuesday', open: '10:00', close: '20:00' },
      { day: 'Wednesday', open: '10:00', close: '20:00' },
      { day: 'Thursday', open: '10:00', close: '21:00' },
      { day: 'Friday', open: '10:00', close: '21:00' },
      { day: 'Saturday', open: '9:00', close: '21:00' },
      { day: 'Sunday', open: '9:00', close: '20:00' },
    ],
    contact: {
      phone: '0412 345 678',
      email: 'hello@aussiebites.com.au',
      instagram: '@aussiebitesfood',
    },
    isOpen: true,
  },
  {
    id: '2',
    name: 'Taco Tiempo',
    description: 'Authentic Mexican street tacos and burritos made with fresh local ingredients and family recipes passed down for generations.',
    image: 'https://images.pexels.com/photos/6468869/pexels-photo-6468869.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    cuisine: 'Mexican',
    rating: 4.5,
    reviewCount: 89,
    menu: [
      {
        id: 'm1',
        name: 'Street Tacos (3)',
        description: 'Corn tortillas with your choice of meat, onions, cilantro, and lime',
        price: 12.95,
        popular: true,
      },
      {
        id: 'm2',
        name: 'Burrito',
        description: 'Flour tortilla filled with beans, rice, cheese, and your choice of meat',
        price: 14.95,
      },
      {
        id: 'm3',
        name: 'Quesadilla',
        description: 'Flour tortilla with melted cheese and optional fillings',
        price: 10.95,
        dietary: ['Vegetarian'],
      },
      {
        id: 'm4',
        name: 'Churros',
        description: 'Fried dough pastry with cinnamon sugar and chocolate dip',
        price: 7.95,
        dietary: ['Vegetarian'],
      },
    ],
    location: {
      text: 'Circular Quay, Sydney',
      coordinates: {
        lat: -33.8618,
        lng: 151.2136,
      },
    },
    schedule: [
      { day: 'Monday', open: 'Closed', close: 'Closed' },
      { day: 'Tuesday', open: '11:00', close: '20:00' },
      { day: 'Wednesday', open: '11:00', close: '20:00' },
      { day: 'Thursday', open: '11:00', close: '20:00' },
      { day: 'Friday', open: '11:00', close: '22:00' },
      { day: 'Saturday', open: '11:00', close: '22:00' },
      { day: 'Sunday', open: '11:00', close: '20:00' },
    ],
    contact: {
      phone: '0487 654 321',
      email: 'info@tacotiempo.com.au',
      instagram: '@tacotiemposyd',
    },
    isOpen: true,
  },
  {
    id: '3',
    name: 'Pasta Express',
    description: 'Fresh pasta made daily with authentic Italian recipes. Quick, delicious, and affordable pasta dishes on the go.',
    image: 'https://images.pexels.com/photos/1267320/pexels-photo-1267320.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    cuisine: 'Italian',
    rating: 4.3,
    reviewCount: 67,
    menu: [
      {
        id: 'm1',
        name: 'Spaghetti Bolognese',
        description: 'Classic spaghetti with rich beef ragu sauce',
        price: 13.95,
      },
      {
        id: 'm2',
        name: 'Fettuccine Alfredo',
        description: 'Fettuccine with creamy parmesan sauce',
        price: 14.95,
        dietary: ['Vegetarian'],
        popular: true,
      },
      {
        id: 'm3',
        name: 'Penne Arrabbiata',
        description: 'Penne with spicy tomato sauce and garlic',
        price: 12.95,
        dietary: ['Vegan'],
      },
      {
        id: 'm4',
        name: 'Tiramisu',
        description: 'Classic Italian dessert with coffee and mascarpone',
        price: 6.95,
        dietary: ['Vegetarian'],
      },
    ],
    location: {
      text: 'Darling Harbour, Sydney',
      coordinates: {
        lat: -33.8727,
        lng: 151.1993,
      },
    },
    schedule: [
      { day: 'Monday', open: '11:00', close: '19:00' },
      { day: 'Tuesday', open: '11:00', close: '19:00' },
      { day: 'Wednesday', open: '11:00', close: '19:00' },
      { day: 'Thursday', open: '11:00', close: '19:00' },
      { day: 'Friday', open: '11:00', close: '21:00' },
      { day: 'Saturday', open: '11:00', close: '21:00' },
      { day: 'Sunday', open: '11:00', close: '19:00' },
    ],
    contact: {
      phone: '0423 456 789',
      email: 'hello@pastaexpress.com.au',
    },
    isOpen: false,
  },
  {
    id: '4',
    name: 'Curry Wheels',
    description: 'Authentic Indian curries and street food made with traditional spices and recipes. Bringing the flavors of India to Sydney streets.',
    image: 'https://images.pexels.com/photos/2474661/pexels-photo-2474661.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    cuisine: 'Indian',
    rating: 4.6,
    reviewCount: 103,
    menu: [
      {
        id: 'm1',
        name: 'Butter Chicken',
        description: 'Tender chicken in a creamy tomato sauce with rice',
        price: 15.95,
        popular: true,
      },
      {
        id: 'm2',
        name: 'Vegetable Samosas (2)',
        description: 'Crispy pastry filled with spiced vegetables',
        price: 8.95,
        dietary: ['Vegetarian'],
      },
      {
        id: 'm3',
        name: 'Chana Masala',
        description: 'Spicy chickpea curry with rice',
        price: 13.95,
        dietary: ['Vegan'],
      },
      {
        id: 'm4',
        name: 'Garlic Naan',
        description: 'Freshly baked flatbread with garlic',
        price: 3.95,
        dietary: ['Vegetarian'],
      },
    ],
    location: {
      text: 'Martin Place, Sydney',
      coordinates: {
        lat: -33.8678,
        lng: 151.2073,
      },
    },
    schedule: [
      { day: 'Monday', open: '11:30', close: '21:00' },
      { day: 'Tuesday', open: '11:30', close: '21:00' },
      { day: 'Wednesday', open: '11:30', close: '21:00' },
      { day: 'Thursday', open: '11:30', close: '21:00' },
      { day: 'Friday', open: '11:30', close: '22:00' },
      { day: 'Saturday', open: '12:00', close: '22:00' },
      { day: 'Sunday', open: '12:00', close: '21:00' },
    ],
    contact: {
      phone: '0498 765 432',
      email: 'info@currywheels.com.au',
      instagram: '@currywheelssyd',
    },
    isOpen: true,
  },
  {
    id: '5',
    name: 'Sweet Dreams',
    description: 'Artisanal gelato, creative desserts, and sweet treats made fresh daily with local ingredients. The perfect sweet escape.',
    image: 'https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    cuisine: 'Dessert',
    rating: 4.8,
    reviewCount: 156,
    menu: [
      {
        id: 'm1',
        name: 'Gelato (2 scoops)',
        description: 'Handcrafted gelato in various flavors',
        price: 8.95,
        dietary: ['Vegetarian'],
        popular: true,
      },
      {
        id: 'm2',
        name: 'Belgian Waffles',
        description: 'Fresh waffles with toppings of your choice',
        price: 12.95,
        dietary: ['Vegetarian'],
      },
      {
        id: 'm3',
        name: 'Pavlova',
        description: 'Classic Australian meringue dessert with fresh fruits',
        price: 9.95,
        dietary: ['Vegetarian'],
      },
      {
        id: 'm4',
        name: 'Vegan Brownie',
        description: 'Rich chocolate brownie made with plant-based ingredients',
        price: 6.95,
        dietary: ['Vegan'],
      },
    ],
    location: {
      text: 'The Rocks, Sydney',
      coordinates: {
        lat: -33.8599,
        lng: 151.2090,
      },
    },
    schedule: [
      { day: 'Monday', open: '12:00', close: '21:00' },
      { day: 'Tuesday', open: '12:00', close: '21:00' },
      { day: 'Wednesday', open: '12:00', close: '21:00' },
      { day: 'Thursday', open: '12:00', close: '21:00' },
      { day: 'Friday', open: '12:00', close: '22:30' },
      { day: 'Saturday', open: '11:00', close: '22:30' },
      { day: 'Sunday', open: '11:00', close: '21:00' },
    ],
    contact: {
      phone: '0434 567 890',
      email: 'hello@sweetdreams.com.au',
      instagram: '@sweetdreamssyd',
    },
    isOpen: true,
  },
];

export const reviews: Review[] = [
  {
    id: 'r1',
    truckId: '1',
    userId: 'u1',
    username: 'Sarah J.',
    userImage: 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 5,
    comment: 'Best Aussie burger I\'ve had in years! The beetroot and pineapple combination is perfect, and the meat pie was just like my grandma used to make. Will definitely be back!',
    date: '2023-12-15',
  },
  {
    id: 'r2',
    truckId: '1',
    userId: 'u2',
    username: 'Michael T.',
    rating: 4,
    comment: 'Really enjoyed the meat pie and sausage roll. The lamington was a bit dry but still good. Great service and friendly staff!',
    date: '2023-12-10',
  },
  {
    id: 'r3',
    truckId: '1',
    userId: 'u3',
    username: 'Emma L.',
    userImage: 'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 5,
    comment: 'Authentic Aussie food right here in Sydney! The burger is massive and delicious. Great location right on Bondi Beach too.',
    date: '2023-11-28',
    reply: {
      text: 'Thanks for your kind words, Emma! We\'re glad you enjoyed your meal. Hope to see you again soon!',
      date: '2023-11-29',
    },
  },
  {
    id: 'r4',
    truckId: '2',
    userId: 'u4',
    username: 'David K.',
    rating: 4,
    comment: 'The tacos were very authentic and flavorful. Loved the street corn as well. Only giving 4 stars because the line was quite long, but the food is definitely worth the wait.',
    date: '2023-12-05',
    reply: {
      text: 'Thank you for your feedback, David! We\'re working on improving our service speed to reduce wait times. Hope to serve you again soon!',
      date: '2023-12-06',
    },
  },
  {
    id: 'r5',
    truckId: '2',
    userId: 'u5',
    username: 'Jessica P.',
    userImage: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    rating: 5,
    comment: 'Best Mexican food in Sydney! The burritos are massive and packed with flavor. Highly recommend the churros for dessert too!',
    date: '2023-11-20',
  },
];

export const dummyUser: User = {
  id: 'u1',
  name: 'Guest User',
  email: 'guest@example.com',
  image: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
  savedTrucks: ['1', '3', '5'],
  reviews: ['r1'],
};

export const dummyOwnerProfile: OwnerProfile = {
  id: 'o1',
  userId: 'u1',
  truckId: '1',
  subscription: 'Basic',
  subscriptionFeatures: [
    'Profile Management',
    'Menu Management',
    'Location Updates',
    'Basic Feedback Management',
  ],
  analytics: {
    profileViews: 1287,
    averageRating: 4.7,
    reviewCount: 124,
    topItems: [
      { name: 'Classic Aussie Burger', count: 542 },
      { name: 'Meat Pie', count: 423 },
      { name: 'Sausage Roll', count: 312 },
      { name: 'Lamington', count: 198 },
    ],
    ratingsByMonth: [
      { month: 'Jan', rating: 4.5 },
      { month: 'Feb', rating: 4.6 },
      { month: 'Mar', rating: 4.6 },
      { month: 'Apr', rating: 4.7 },
      { month: 'May', rating: 4.7 },
      { month: 'Jun', rating: 4.8 },
    ],
  },
};

export const cuisineOptions: Cuisine[] = [
  'Australian',
  'Italian',
  'Mexican',
  'Asian',
  'Indian',
  'Mediterranean',
  'Dessert',
  'Vegan',
  'Seafood',
  'BBQ'
];

export const locationOptions = [
  'Bondi Beach',
  'Circular Quay',
  'Darling Harbour',
  'The Rocks',
  'Martin Place',
  'Surry Hills',
  'Newtown',
  'Manly',
  'Parramatta',
  'Chatswood'
];